branch-defaults:
  main:
    environment: Django-test-server-env
environment-defaults:
  Django-test-server-env:
    branch: main
    repository: django-eb-test
global:
  application_name: Django-test-server
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
